apiVersion: v1
kind: Namespace
metadata:
  name: template
---
apiVersion: packages.crossplane.io/v1alpha1
kind: ClusterPackageInstall
metadata:
  name: provider-template
  namespace: template
spec:
  package: "crossplanebook/provider-template:latest"